project:
  seed: 42

paths:
  data_root: ./Рамановские спектры
  outputs: ./outputs

data:
  sample_agg_features: [median, mean, std, q25, q75]
  append_first_derivative: true
  include_region_feature: false
  centers_to_run: [1500, 2900]

  use_raw_cache: true
  force_reload_raw_cache: false

  use_aligned_cache: true
  force_rebuild_aligned_cache: false

  use_samplewise_cache: true
  force_rebuild_samplewise_cache: false

preprocessing:
  enabled: true

  crop_range: [700, 1800]

  crop_ranges_by_center:
    "1500": [700, 1800]
    "2900": [2600, 3200]

  despike_threshold: 6.0
  despike_window: 3
  smooth_window: 11
  smooth_polyorder: 3
  baseline_lam: 100000.0
  baseline_p: 0.01
  baseline_niter: 10
  normalization: l2

training:
  cv_strategy: stratified_group
  group_kfold_splits: 3

  datasets:
    samplewise: true
    pixelwise: false

  models:
    linear_svm: false
    pca_svm: false
    rf: false
    extra_trees: true
    catboost: true
    pls_logreg: true
    logreg: false

  ensemble:
    enabled: true
    name: ensemble_soft
    members: [extra_trees, catboost, pls_logreg]
    weights:
      extra_trees: 1.0
      catboost: 1.0
      pls_logreg: 1.0

  extra_trees:
    n_estimators: 1000
    max_depth: null
    min_samples_split: 4
    min_samples_leaf: 2
    max_features: sqrt
    class_weight: balanced_subsample

  catboost:
    iterations: 500
    depth: 5
    learning_rate: 0.05
    thread_count: 1
    l2_leaf_reg: 5.0
    subsample: 0.9
    auto_class_weights: Balanced

  pls_logreg:
    n_components: 8
    C: 1.0
    class_weight: balanced
    max_iter: 5000

interpretation:
  rf_top_k: 30
