project:
  seed: 42

paths:
  data_root: ./Рамановские спектры
  outputs: ./outputs

data:
  sample_agg_method: median

  include_region_feature: true
  centers_to_run: [1500, 2900]

  use_raw_cache: true
  force_reload_raw_cache: false

  use_aligned_cache: true
  force_rebuild_aligned_cache: false

  use_samplewise_cache: true
  force_rebuild_samplewise_cache: false

preprocessing:
  enabled: true

  crop_range: [700, 1800]

  crop_ranges_by_center:
    "1500": [700, 1800]
    "2900": [2600, 3200]

  despike_threshold: 6.0
  despike_window: 3
  smooth_window: 11
  smooth_polyorder: 3
  baseline_lam: 100000.0
  baseline_p: 0.01
  baseline_niter: 10
  normalization: l2

training:
  group_kfold_splits: 4

  datasets:
    samplewise: true
    pixelwise: false

  models:
    pca_svm: false
    rf: true

eda:
  plot_raw_vs_processed_files: 3

interpretation:
  rf_top_k: 30
